;PWM.ASM
    __CONFIG 0X3FF9
#INCLUDE "P16F873.INC"
    ORG 0   
    GOTO INIT
    ORG 4   
    GOTO INT
INIT        
;INIT I/O   
    BSF   STATUS,RP0
    MOVLW 0X01
    MOVWF TRISA
    CLRF  TRISC     
    BCF   STATUS,RP0
;INIT A/D
    MOVLW 0X81   
    MOVWF ADCON0   
    BSF   STATUS,RP0
    MOVLW 0X0E   
    MOVWF ADCON1   
    BCF   STATUS,RP0
;INIT TIMER
    CLRF  TMR2
    CLRF  CCPR1L
    BSF   STATUS,RP0
    MOVLW 0XFF
    MOVWF PR2
    BCF   STATUS,RP0
    MOVLW 0X06
    MOVWF T2CON  
    MOVLW 0X0C 
    MOVWF CCP1CON
;INIT PWM
    CLRF  TMR1H 
    CLRF  TMR1L
    MOVLW 0X09
    MOVWF CCPR2H
    MOVLW 0XC4
    MOVWF CCPR2L
    MOVLW 0X01
    MOVWF T1CON
    MOVLW 0X0B
    MOVWF CCP2CON
;INIT INTERRUPT
    BSF   STATUS,RP0
    MOVLW 0X01
    MOVWF PIE2
    BCF   STATUS,RP0
    MOVLW 0XC0
    MOVWF INTCON
;MAIN LOOP
WAIT
    GOTO  WAIT
;INTERRUPT
INT
    CLRF  PIR2
ADCK
    BTFSC ADCON0,GO
    GOTO  ADCK
    MOVF  ADRESH,W
    MOVWF CCPR1L
    MOVWF PORTC
    RETFIE
;
END
